// <auto-generated />
using System;
using FinanceProject_WebApp_1_1.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceProject_WebApp_1_1.Migrations
{
    [DbContext(typeof(FinanceDBContext))]
    [Migration("20230827183656_Test")]
    partial class Test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinanceProject_WebApp_1_1.Models.Tickers", b =>
                {
                    b.Property<string>("Ticker")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("TickerList");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Cik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Composite_Figi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Last_Updated_Utc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Locale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Market")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Primary_Exchange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Share_Class_Figi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Ticker");

                    b.ToTable("TickerList");
                });
#pragma warning restore 612, 618
        }
    }
}
